// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd42tRLPu_Uy9-g3Q2aE4SWdOlHKHSbcA',
    appId: '1:233612908115:web:0c798ff23aa4a3d437d8a6',
    messagingSenderId: '233612908115',
    projectId: 'chatapptute-2df12',
    authDomain: 'chatapptute-2df12.firebaseapp.com',
    storageBucket: 'chatapptute-2df12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJKweiPckyyQ6iSFSvkIy6V0fMy2V59eY',
    appId: '1:233612908115:android:9602323f5a5fc54837d8a6',
    messagingSenderId: '233612908115',
    projectId: 'chatapptute-2df12',
    storageBucket: 'chatapptute-2df12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ywiljFet_vyHGO5_LJNoCSiyyMFUo6Y',
    appId: '1:233612908115:ios:9eaa8263fcdb11d037d8a6',
    messagingSenderId: '233612908115',
    projectId: 'chatapptute-2df12',
    storageBucket: 'chatapptute-2df12.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9ywiljFet_vyHGO5_LJNoCSiyyMFUo6Y',
    appId: '1:233612908115:ios:0cd08b03531ccd0437d8a6',
    messagingSenderId: '233612908115',
    projectId: 'chatapptute-2df12',
    storageBucket: 'chatapptute-2df12.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
